- name: Get Helm apt-key
  apt_key: 
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Adding apt repository for Helm
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm.list

- name: Install helm packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - helm

#- name: Install chartmuseum
#  shell: curl https://raw.githubusercontent.com/helm/chartmuseum/main/scripts/get-chartmuseum | bash >> chartmuseum.log
#  args: 
#    chdir: $HOME
#    creates: chartmuseum.log