- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable Swap
  command: swapoff -a

- name: Update apt-get repo and cache
  apt: 
    update_cache: yes 

- name: Installing Docker
  apt: 
    name: "{{ packages }}"
    update_cache: false
    state: present
  vars:
    packages:
      - docker.io

- name: Reload configs
  systemd: 
    daemon_reload: yes

- name: 'Add "{{ ansible_ssh_user }}" user to docker group'
  user:
    name: "{{ ansible_ssh_user }}"
    group: docker

- name: Driver docker
  copy:
    src: daemon.json 
    dest: /etc/docker/daemon.json 

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes