---
- name: Remove file default netplan file
  file:
    path: /etc/netplan/00-installer-config.yaml
    state: absent

- name: Setando ip statico Ubuntu
  template:
    src: 50-cloud-init.yaml
    dest: /etc/netplan/50-cloud-init.yaml
    force: yes
    owner: root
    group: root
  when: ansible_distribution == 'Debian' or ansible_distribution== 'Ubuntu'

- name: netplan
  command: netplan apply
