network:
  version: 2
  renderer: networkd
  ethernets:
    {{ ansible_default_ipv4.alias }}:
      dhcp4: no
      addresses: [{{ ansible_default_ipv4.address }}/24]
      gateway4: {{ ansible_default_ipv4.gateway }}
      dhcp6: false
      optional: true
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]