- name: Ingress-controller file
  template:
    src: nginx_ingress.j2
    dest: /tmp/ingress_controller.yaml
    force: yes
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Copy k8s manifests
  copy:
    src: ../../k8s/manifests/
    dest: /home/{{ ansible_ssh_user }}/manifests/

- name: Pause for 5 minutes to build k8s cluster
  pause:
    seconds: "5"

#- name: Apply ingress controller
#  shell: kubectl apply -f /tmp/ingress_controller.yaml >> ingress_controller.log
#  args: 
#    chdir: $HOME
#    creates: ingress_controller.log

- name: Pause for 5 minutes to build k8s cluster
  pause:
    seconds: "10"
   
- name: Apply metric-server
  shell: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml >> metric_server.log
  args: 
    chdir: $HOME
    creates: metric_server.log

