---
kubernetes_minor_version: "1.30"
kubernetes_apt_key_url: "https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor_version }}/deb/Release.key"
kubernetes_apt_keyring_path: /etc/apt/keyrings/kubernetes.asc
kubernetes_apt_repository: >-
  deb [signed-by={{ kubernetes_apt_keyring_path }}]
  https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_minor_version }}/deb/ /

kubernetes_prerequisite_packages:
  - apt-transport-https
  - ca-certificates
  - conntrack
  - curl
  - ebtables
  - ethtool
  - gpg
  - socat

kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
  - containerd

kubernetes_kernel_modules:
  - overlay
  - br_netfilter

kubernetes_sysctl_settings:
  net.bridge.bridge-nf-call-iptables: "1"
  net.bridge.bridge-nf-call-ip6tables: "1"
  net.ipv4.ip_forward: "1"

kubernetes_containerd_config_path: /etc/containerd/config.toml
kubernetes_pause_image: registry.k8s.io/pause:3.9
