apiVersion: apps/v1
kind: Deployment
metadata:
  name: getip-deployment
  labels:
    app: getip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: getip
  template:
    metadata:
      labels:
        app: getip
    spec:
      containers:
        - name: getip
          image: duran750/getvalidip
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 300m
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: getip-svc
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: getip
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: getip-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: simplecrud.com
    http:
      paths:
      - backend:
          service:
            name: getip-svc
            port:
              number: 3001
        path: /getip
        pathType: Prefix

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: getip-deployment
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: getip-deployment
  targetCPUUtilizationPercentage: 50