apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kibana
spec:
  rules:
    - host: kibana.local
      http:
        paths: 
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kibana-kibana
              port:
                number: 5601