apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  DB_PASS: 7KAVTF745s56yryN
  DB_SERVER: db-svc
  DB_USER: fastapi

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: duran750/k8s-iac
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: api-configmap
        resources:
          limits: 
            cpu: 500m
          requests:
            cpu: 300m        
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  selector:
    app: api

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-deployment
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  targetCPUUtilizationPercentage: 80