apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: app.prova
    http:
      paths: 
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-svc
            port:
              number: 80