name: DeployTerraform

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-infra:
    name: Deploy Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        run: terraform plan -input=false -var="public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var="public_key=${{ secrets.SSH_PUBLIC_KEY }}"

      - name: Terraform Output
        run: terraform output -no-color
