name: DestroyTerraform

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  destroy-infra:
    name: Destroy Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var="public_key=${{ secrets.SSH_PUBLIC_KEY }}"
