name: DeployTerraform

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: terraform
          path: ${{ github.workspace }}/iac/terraform

  deploy-infra:
    name: Deploy Infra Dev
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ github.workspace }}/iac/terraform

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #ARM_CLIENT_ID: ${{ secrets.TF_ARM_CLIENT_ID }}
      #ARM_CLIENT_SECRET: ${{ secrets.TF_ARM_CLIENT_SECRET }}
      #ARM_SUBSCRIPTION_ID: ${{ secrets.TF_ARM_SUBSCRIPTION_ID }}
      #ARM_TENANT_ID: ${{ secrets.TF_ARM_TENNANT_ID }}

    needs: build
    steps:
      - name: Download Terraform
        uses: actions/download-artifact@v2
        with:
          name: terraform
          path: ${{ github.workspace }}/iac/terraform


      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init  -backend-config="access_key=AWS_ACCESS_KEY_ID" -backend-config="secret_key=AWS_SECRET_ACCESS_KEY"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -lock=false
        continue-on-error: true
  
      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false